[TASK_MASTER]

TASK_ID= 1
TASK_TYPE="FILE_INGESTION"
TASK_DESC="Bulk load all files from Sharepoint/S3 to Landing Layer(SF) of mROI"
ACTIVE_FLAG="Y"
TASK_AREA="FF_TO_LND"
REC_INSERT_DTTM="2024-05-07"
REC_UPDATE_DTTM="2024-05-07"